### ISSUE TITLE
Deep Aether mod for Minecraft

### ISSUE THREAD

**Issue by junginon** [RazorDevs/quark-aether#1]
I had been playing with the added stratus armor in addition of the ring and gloves and it was awesome i cant live without the jump boost elytra combo but just now it stopped giving me the jump boost when i wear the armor im not sure why. has this happened to anyone else?

**Comment by darksonic300** [comment]
Sorry, but this is the Ascended Quark github repository and not Deep Aether's.
Please send a detailed explanation of the issue [here](https://github.com/RazorDevs/Deep-Aether/issues).
