### ISSUE TITLE
Crash on custom Modpack on 1.20.1

### ISSUE THREAD

**Issue by Handrail9** [RazorDevs/quark-aether#3]
Hello, let me know if I am incorrect and it isn't this mod crashing my game. I make the assumption as my game will launch without Ascended Quark but not with it. This started happening after I updated quark and zeta to the latest versions so I suspect there may have been a breaking change but I may be wrong. Let me know if this is a correlation and not causation sitch or if there's something I'm doing wrong. Thanks!
[latest.log](https://github.com/user-attachments/files/16517701/latest.log)
[mods.txt](https://github.com/user-attachments/files/16517719/mods.txt)

**Comment by darksonic300** [comment]
It is Ascended Quark. Zeta updated and broke it, but going to be fixed soon.
